from typing import Protocol
from uuid import UUID

from src.domain.events import OutboxEvent
from src.domain.lead import Lead


class LeadRepository(Protocol):
    async def add(self, lead: Lead) -> None: ...
    async def get_by_id(self, lead_id: UUID) -> Lead | None: ...


class OutboxRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...
    async def get_unpublished(self) -> list[OutboxEvent]: ...
    async def mark_as_published(self, event_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    @property
    def leads(self) -> LeadRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class MessageProducer(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def send(self, topic: str, key: str, value: bytes) -> None: ...
