from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from src.domain.events import InboundEvent, OutboxEvent
from src.domain.lead import Lead, LeadStatus


class LeadRepository(Protocol):
    async def add(self, lead: Lead) -> None: ...
    async def get_by_id(self, lead_id: UUID) -> Lead | None: ...
    async def update_status(self, lead_id: UUID, status: LeadStatus) -> None: ...


class OutboxRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...
    async def get_unpublished(self) -> list[OutboxEvent]: ...
    async def mark_as_published(self, event_id: UUID) -> None: ...


class InboundEventRepository(Protocol):
    async def exists(self, event_id: UUID) -> bool: ...
    async def add(self, event: InboundEvent) -> None: ...


class UnitOfWork(Protocol):
    @property
    def leads(self) -> LeadRepository: ...

    @property
    def outbox(self) -> OutboxRepository: ...

    @property
    def inbound(self) -> InboundEventRepository: ...

    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class MessageProducer(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def send(self, topic: str, key: str, value: bytes) -> None: ...


@dataclass(slots=True)
class ConsumerMessage:
    topic: str
    key: bytes | None
    value: bytes | None
    offset: int
    partition: int


class MessageConsumer(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def poll(self, timeout_ms: int) -> list[ConsumerMessage]: ...
    async def commit(self) -> None: ...
